---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  vars:
    molecule_repo_file:
      RedHat:
        "8": "ubi.repo"
      CentOS:
        "9": "centos.repo"
    molecule_repo_name:
      RedHat:
        "8": "ubi-8-codeready-builder"
      CentOS:
        "9": "crb"
    molecule_repo_package:
      RedHat:
        "8": "libaec"
      CentOS:
        "9": "zlib-static"
  tasks:
    - name: SmokeTests
      debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family}}"
          - "ansible_system  => {{ ansible_system }}"

    - name: Test if repository exists and is enabled
      community.general.ini_file:
        path: "/etc/yum.repos.d/{{ molecule_repo_file[ansible_distribution][ansible_distribution_major_version] }}"
        section: "{{ molecule_repo_name[ansible_distribution][ansible_distribution_major_version] }}"
        option: enabled
        value: "1"
        mode: "0644"
      register: molecule_repository
      failed_when: (molecule_repository is changed) or (molecule_repository is failed)

    - name: Check package is installable from repository
      ansible.builtin.yum:
        name: "{{ molecule_repo_package[ansible_distribution][ansible_distribution_major_version] }}"
        state: present
      register: package_installed
